version: "3"
services:
  protoctest:
    image: registry.gitlab.com/imerkle/protocbuild:latest
    container_name: protoctest
    environment:
      - SSH_KEY=${SSH_KEY}
      - COMMIT_USER=${GITLAB_USER_NAME}
      - COMMIT_EMAIL=${GITLAB_USER_EMAIL}
      - DIND_WORKSPACE=${CI_PROJECT_DIR}
      - WORKSPACE_ROOT=/workspace/
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
